[settings]
python_compile = false
experimental = true

[tools]
ripgrep = "latest"
terraform-ls = "latest"
awscli = "latest"
opentofu = "latest"
usage = "latest"
go = "latest"
terraform = "latest"
direnv = "latest"
pre-commit = "latest"
jq = "latest"
yq = "latest"
nodejs = "21.2.0"
helm = "latest"
kubectx = "latest"
flux2 = "latest"
sops = "3.8.1"
age = "latest"
qdns = "latest"
k9s = "latest"
cilium-cli = "latest"
cilium-hubble = "latest"
calicoctl = "3.27.0"
kind = "latest"
eza = "latest"
bat = "latest"
marp-cli = "latest"
terragrunt = "0.72.0"
terraform-docs = "latest"
clusterctl = "latest"
gojq = "latest"
jqp = "latest"
shellcheck = "latest"
zoxide = "latest"
github-cli = "latest"
delta = "latest"
chezmoi = "latest"
fzf = "latest"
tflint = "latest"
kubectl = "latest"
fd = "latest"
yarn = "latest"
glab = "1.46"
redis-cli = "7.2.6"
ruby = "latest"
node = "latest"
pandoc = "latest"
kubecolor = "latest"
dive = "latest"
helmfile = "latest"
trivy = "latest"
crane = "latest"
talosctl = "latest"
ruff = "latest"
"go:github.com/dlvhdr/diffnav" = "latest"
"gem:solargraph" = "latest"
